<?php
//TABLES
define("this","this");
define("attachments","attachments");
define("bans","bans");
define("pastes","pastes");
define("bbcode","bbcode");
define("drafts","drafts");
define("forms","forms");
define("forum","forum");
define("general","general");
define("grouppermissions","grouppermissions");
define("groups","groups");
define("images","images");
define("input","input");
define("modules","modules");
define("permissions","permissions");
define("post","post");
define("ranks","ranks");
define("ratings","ratings");
define("report","report");
define("sessions","sessions");
define("topic","topic");
define("usergroups","usergroups");
define("users","users");
define("warn","warn");
?>
